name: Build and Release Ghost Theme

on: [push]

jobs:
  build-and-release:
    name: Build and Release Ghost Theme

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: build
      uses: foolscapcon/action-build-ghost-theme@v1.0.6

    - name: upload
      uses: svenstaro/upload-release-action@1.0.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.build.outputs.file }}
        asset_name: ${{ steps.build.outputs.name }}
        tag: ${{ steps.build.outputs.tag }}

