name: Build and Release Ghost Theme

on: [push]

jobs:
  build-and-release:
    name: Build and Release Ghost Theme

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build Ghost Theme
      id: build
      uses: foolscapcon/action-build-ghost-theme@v1.0.2

    - name: Upload Theme Zip File to Release
      id: upload
      uses: svenstaro/upload-release-action@1.0.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.build.outputs.RELEASE_FILE }}
        asset_name: ${{ steps.build.outputs.RELEASE_NAME }}
        tag: ${{ steps.build.outputs.RELEASE_TAG }}

