name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Ghost Theme Zip File
      uses: foolscapcon/action-build-ghost-theme@v1.0.0
      image: Dockerfile
      outputs:
        release_file:
          description: 'theme zip filename'
        release_name:
          description: 'theme filename sans extension'
        release_tag:
          description: 'theme release tag'      
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@1.0.1

      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ outputs.RELEASE_FILE }}
        asset_name: ${{ outpus.RELEASE_NAME }}
        tag: ${{ outputs.RELEASE_TAG }}

