name: Build and Release Ghost Theme

on: [push]

jobs:
  build-and-release:
    name: Build and Release Ghost Theme

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: build
      id: build
      uses: foolscapcon/action-build-ghost-theme@v1.0.8
    - name: examine-job
      run: echo "${{ toJson(jobs.build-and-release.steps.working-directory) }}"
    - name: examine0
      run: echo "${{ toJson(steps) }}"
    - name: examine1
      run:  echo "${{ toJson(steps.build) }}"
    - name: examine2
      run:  echo "${{ toJson(steps.build.outputs) }}"
    - name: examine3
      run:  echo "${{ steps.build.outputs.release_file }}"
    - name: examine4
      run:  echo "${{ steps.build.outputs.release_name }}"
    - name: examine5
      run:  ls -al ${GITHUB_WORKSPACE}
    - name: examine6
      run:  echo "${GITHUB_WORKSPACE}"
    - name: examine7
      run:  ls -al "${GITHUB_WORKSPACE}/${{ steps.build.outputs.release_name }}.zip"
    - name: examine8
      run:  ls -al "${GITHUB_WORKSPACE}/${{ steps.build.outputs.release_file }}"
    - name: examine9
      run:  ls -al ${{ steps.build.outputs.release_file }}


    - name: artifact
      uses: actions/upload-artifact@master
      with:
        path: ${{ steps.build.outputs.release_file }}
        name: ${{ steps.build.outputs.release_name }}

    - name: upload
      uses: svenstaro/upload-release-action@1.0.1
      with:
        file: ${{ steps.build.outputs.file }}
        asset_name: ${{ steps.build.outputs.name }}
        tag: ${{ steps.build.outputs.tag }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
