name: Build and Release Ghost Theme

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: build
      description: Build Ghost Theme Zip File
      uses: foolscapcon/action-build-ghost-theme@latest

    - name: upload
      description: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@1.0.1

      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.build.outputs.RELEASE_FILE }}
        asset_name: ${{ steps.build.outputs.RELEASE_NAME }}
        tag: ${{ steps.build.outputs.RELEASE_TAG }}

